import os
import sys
from logger import StructuredLogger
from pathlib import Path

log = StructuredLogger("Cleanup", "TRACE", "CaseBriefs.log", True, None, True, True)


def clean_dir(path: Path, ignore_dirs: list[Path] = []):
    relative_print_path = path.relative_to(Path(__file__).absolute().parent)
    log.info(f"Cleaning directory: {relative_print_path}")
    for file in path.iterdir():
        curr_path = file.absolute()
        curr_relative_print_path = curr_path.relative_to(
            Path(__file__).absolute().parent
        )
        if os.path.isfile(curr_path):
            log.trace(f"Found file: {curr_relative_print_path}")
            if file.suffixes in (
                [".aux"],
                [".fdb_latexmk"],
                [".fls"],
                [".idx"],
                [".ilg"],
                [".ind"],
                [".log"],
                [".out"],
                [".synctex", ".gz"],
                [".synctex(busy)"],
                [".toc"],
            ):
                log.trace(f"File in glob for deletion")
                log.debug(f"Removing file: {curr_relative_print_path}")
                os.remove(curr_path)
        elif os.path.isdir(curr_path):
            if curr_path in ignore_dirs:
                log.trace(
                    f"Directory in ignore list, skipping: {curr_relative_print_path}"
                )
                ignore_dirs = [d for d in ignore_dirs if d != curr_path]
                continue
            log.debug(f"Pivoting to directory: {curr_relative_print_path}")
            clean_dir(curr_path, ignore_dirs=ignore_dirs)


if __name__ == "__main__":
    if sys.argv[1:] == ["--help"] or sys.argv[1:] == ["-h"]:
        print("Usage: python cleanup.py [--help | -h | path]")
        print("Cleans up auxiliary files generated by LaTeX compilation.")
        print("If no path is provided, the current directory is used.")
        sys.exit(0)
    if len(sys.argv) > 1:
        target_path = Path(sys.argv[1]).absolute()
        if not target_path.exists() or not target_path.is_dir():
            print(f"Error: Provided path '{target_path}' is not a valid directory.")
            sys.exit(1)
        clean_dir(
            target_path,
            ignore_dirs=[
                target_path / ".venv",
                target_path / "__pycache__",
                target_path / ".git",
                target_path / ".mypy_cache",
                target_path / "dist",
                target_path / "build",
            ],
        )
        sys.exit(0)
    else:
        curr_path = Path(__file__).absolute().parent
        clean_dir(
            curr_path,
            ignore_dirs=[
                curr_path / ".venv",
                curr_path / "__pycache__",
                curr_path / ".git",
                curr_path / ".mypy_cache",
                curr_path / "dist",
                curr_path / "build",
            ],
        )
