-- Exported SQLite data (data only)
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO "Courses" ("id", "name") VALUES (1, 'Civil Procedure');
INSERT INTO "Courses" ("id", "name") VALUES (2, 'Contracts');
INSERT INTO "Courses" ("id", "name") VALUES (3, 'Torts');
INSERT INTO "Courses" ("id", "name") VALUES (4, 'Legal Practice');
INSERT INTO "Subjects" ("id", "name") VALUES (1, 'False Imprisonment');
INSERT INTO "Subjects" ("id", "name") VALUES (2, 'Mistake');
INSERT INTO "Subjects" ("id", "name") VALUES (4, 'Breach of Contract');
INSERT INTO "Subjects" ("id", "name") VALUES (5, 'Unilateral Contract');
INSERT INTO "Subjects" ("id", "name") VALUES (6, 'Negligence');
INSERT INTO "Subjects" ("id", "name") VALUES (7, 'Car');
INSERT INTO "Subjects" ("id", "name") VALUES (8, 'Reasonable Care');
INSERT INTO "Subjects" ("id", "name") VALUES (9, 'Assumpsit');
INSERT INTO "Subjects" ("id", "name") VALUES (11, 'Offer');
INSERT INTO "Subjects" ("id", "name") VALUES (12, 'Warranty');
INSERT INTO "Subjects" ("id", "name") VALUES (15, 'Battery');
INSERT INTO "Subjects" ("id", "name") VALUES (16, 'Race');
INSERT INTO "Subjects" ("id", "name") VALUES (20, 'Mutual Assent');
INSERT INTO "Subjects" ("id", "name") VALUES (23, 'Implied-in-fact');
INSERT INTO "Subjects" ("id", "name") VALUES (25, 'Tresspass (common law)');
INSERT INTO "Subjects" ("id", "name") VALUES (29, 'Intent');
INSERT INTO "Subjects" ("id", "name") VALUES (30, 'Browsewrap');
INSERT INTO "Subjects" ("id", "name") VALUES (35, 'Intentional Infliction of Emotional Distress');
INSERT INTO "Subjects" ("id", "name") VALUES (42, 'Property Damage');
INSERT INTO "Subjects" ("id", "name") VALUES (44, 'Minor');
INSERT INTO "Subjects" ("id", "name") VALUES (46, 'Implied Contract');
INSERT INTO "Subjects" ("id", "name") VALUES (47, 'Silence as Acceptance');
INSERT INTO "Subjects" ("id", "name") VALUES (48, 'Assault');
INSERT INTO "Subjects" ("id", "name") VALUES (49, 'Revocation');
INSERT INTO "Subjects" ("id", "name") VALUES (50, 'Trespass to Land');
INSERT INTO "Opinions" ("id", "author", "opinion_text") VALUES (1, 'Lehman, J', 'Defendant''s letter constituted a promise to accept payment if Plaintiff comes and offers it. The distinction between "offering payment" and "tendering payment" in this situation can only confuse the results. If the offer was to accept payment, but allows the offerer to deny that the promise is binding until after they have accepted it then the offer doesn''t mean anything.');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Hardy', 'LaBelle''s Distributing Co', '203 Mont. 263, 661, P.2d 35 (1983)', 'Torts', 'Plaintiff (Hardy) was hired by Defendant (LaBelle''s Distributing Co) as a sales clerk in the jewelry department. On December 9, another employee thought they saw plaintiff steal a watch from a display and reported that suspicion to the assistant manager. The next day, the assistant manager told plaintiff that he wanted to give her a tour of the office, but then led her to a room with police officers and the loss prevention manager. They told her about the accusation, which she denied, and asked her to take a poligraph, which she accepted and passed. After the interaction, plaintiff filed a suit for false imprisonment based on her being brought to the room and expected to stay under false pretenses.', 'Trial Court: In favor of Defendant
Appeal: In favor of Defendant', 'Does a situation in which someone feels compelled to stay somewhere constitute false imprisonment?', 'No; Ruling Affirmed', 'The two key elements of false imprisonment are the restraint of an individual against their will, by either acts or merely by words which they fear to disregard, and the unlawfullness of such restraint', 'Given that plaintiff admitted that she would have wanted to go clear up the accusations if she had known why she was being brought to the office, she cannot be said to have been restrained. Particularly because she was never told not to leave directly or otherwise.', 'HardyVLaBelle', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Ranson', 'Kitner', '31 Ill.App. 241. (1889)', 'Torts', 'The defendant was hunting for wolves and saw plaintiff''s dog. The dog resembed a wolf and the defendant killed it as such.', 'Trial Court: In favor of Plaintiff
Appeal: In favor of Plaintiff', 'Is the defendant liable for damages caused by a mistake that was made in good faith?', 'Yes; Judgment Affirmed', 'A defendant holds liability for damage that results from a mistake', 'The judge intentionally uses the term "mistake" to indicate that the damages, though made in good faith, were intentional and therefore there is liability', 'RansonVKitner', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Parvi', 'City of Kingston', '41 N.Y.2d 553, 362 N.E.2d 960, 394 N.Y.S.2d 161 (1977)', 'Torts', 'The defendant (The City of Kingston Police) responded to a complaint in which two brothers were fighting and plaintiff (Parvi) was trying to calm them down. According to the defendants, all three were showing "the effects of alcohol." When plaintiff told the police he didn''t have anywhere to go, they took him outside the city limits and left him there to "dry out." Plaintiff then wandered into traffic and was hit by a car.', 'Trial Court: In favor of defendant
Appeal: In favor of defendant
Supreme Court: In favor of plaintiff', 'If the plaintiff was too drunk to have a recollection of their confinement, does that undermine their cognisense of their captivity?', 'No; Reversed and remanded', 'there is no liability for intentionally confining another unless the person physically restrained knows of the confinement or is harmed by it', '', 'ParviVKingston', 'the plaintiff must show that: 
(1) the defendant intended to confine him, 
(2) the plaintiff was conscious of the confinement, 
(3) the plaintiff did not consent to the confinement and 
(4) the confinement was not otherwise privileged');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Kolodziej', 'Mason', '774 F.3d 736 (2014)', 'Contracts', 'The defendant (James Mason) was a defense attorney defending a high-profile client accused of quadruple homicide. The case relied on the client having made it off of an airplane and arriving back at a specific hotel 28 minutes later. In expressing his incredulity at this possibility, the defendant said in an NBC interview that "if anyone could give him evidence that this was possible he would give them $1,000,000". The plaintiff (Kolodziej), then a law student, saw this interview and decided to take it as a challenge. Based on the information he had about the case, he attempted the feat and then sent proof to defendant.', 'Trial Court: In favor of defendant
Appeal: In favor of defendant', '', '', 'Spoken words, particularly when said hyperbolically or in such a way that a reasonable person would interpret them as such, cannot be enforced', '', 'KolodziejVMason', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Cohen', 'Petty', '62 App.D.C. 187, 65 F.2d 820 (1933)', 'Torts', 'The plaintiff was riding in a car driven by the defendant, when the defendant was suddenly stricken by an illness that resulted in them passing out behind the wheel. 
The defendant testified that he knew himself to be in good help and had never fainted before. 
The defendant wasn''t driving recklessly and he did not feel ill until moments before he passed out.', 'Trial Court: In favor of Defendant
Appeal: In favor of Defendant', 'Can a defendant struck with a sudden and unexpected illness that results in damages to a plaintiff be held liable?', 'No; Previous Ruling Affirmed', 'Unexpected and accidental "acts of god" cannot be used to hold someone liable for negligence', 'There was no evidence presented that would indicate that any reasonable level of care could have prevented the events from happening, therefore it is unreasonable to hold the defendant liable for negligence', 'CohenVPetty', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Hawkins', 'McGee', '84 N.H. 114, 146 A. 641 (N.H. 1929)', 'Contracts', 'A young man suffered an electrical burn on his hand that left him with scar tissue on his hand. He is solicited by a doctor who offers to perform a skin graft from his chest to his hand. He claimed that the man would recover from the surgery in 3-4 days and would be left with a "perfect hand". 
The surgery was botched by the surgeon and resulted in an infection and hair grew from his hand. 
The man''s usage of the hand was impacted and he sued for breach of contract.', 'Trial Court (Jury Verdict): In favor of the Plaintiff ($3,000)
Trial Court (Directed Verdict): Remit the damages in excess of ($500)
Appeal: In favor of the Plaintiff [New trial ordered]
Settlement: ($1,300)', 'Does the defendants promise to give the plaintiff a "perfect hand" constitute a warranty for the surgery? 
Is this impacted by the fact the doctor solicited the patient for the surgery?', 'Yes; New trial ordered', 'The verbal warranty provided by the doctor entitled the patient to expectancy damages', 'The previous instructions provided to the jury failed in both its points:
- The pain and suffering felt by the patient where irrelevant because they would have been experienced regardless of the results of the surgery
- The warranty provided by the doctor entitles the patient to more than just restitution damages', 'HawkinsVMcGee', 'The writ (the lawsuit) included a count of negligence, and assumpsit.
Negligence - Malpractice (struck because the surgery was known to be experimental)
Assumpsit -');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Lefkowitz', 'Greater Minneapolis Surplus Store, Inc', '251 Minn. 188, 86 N.W.2d 689 (1957)', 'Contracts', 'Defendant (Greater Minneapolis Surplus Store) posted an advertisement in the newspaper announcing a number of fur coats (valued either at $100 or $139.50) were to be sold for $1 each to the first people to buy them. Plaintiff attempted to purchase the coats at each opportunity, being the first person at the store after both advertisements were made. However, the defendant denied the sale, citing that by "house rules" the offers were meant for women. Plaintiff sued for breach of contract.', 'Trial Court: In favor of plaintiff ($138.50)
Appeal: In favor of plaintiff', 'Does a newspaper advertisement that indicates a well-defined sale constitute a unilateral contract?', 'Yes; Ruling affirmed', 'A newspaper or circular letter relating to the sale of articles may be construed by the court as constituting an offer, acceptance of which would complete the contract', 'The invocation of "house rules" does not override this offer because there was nowhere stated any ability to negotiate or modify the offer as presented.', 'LefkowitzVSurplus', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Fisher', 'Carrousel Moter Hotel, Inc', '424 S.W.2d 627 (1967)', 'Torts', 'The plaintiff (Fisher) was a NASA mathematician attending a professional conference at defendant''s (Carrousel Moter Hotel, Inc) that included a buffet luncheon. 
While waiting in line with a plate to get said food, an employee of the defendant approached the plaintiff and grabbed the plate from his hand saying that a "Negro could not be served in the club."
Though the plaintiff was not actually touched, and was in not afraid for his wellbeing, he was embarrased and hurt by the conduct.', 'Trial Court (Jury): In favor of the plaintiff ($400 in damages and $500 in punative damage)
Trial Court (Judge): Overruled in favor of the defendant
Appeal: Affirmed in favor of defendant
Supreme Court: In favor of plaintiff (Reversed; original $900 rendered)', 'Does a battery necessarily require physical contact?', 'No; Reversed', 'To constitute an assault and battery, it is not necessary to touch the plaintiff’s body or even his clothing; knocking or snatching anything from plaintiff’s hand or touching anything connected with his person, when done in an offensive manner, is sufficient', '"To constitute an assault and battery, it is not necessary to touch the plaintiff’s body or even his clothing; knocking or snatching anything from plaintiff’s hand or touching anything connected with his person, when done in an offensive manner, is sufficient."', 'FisherVCMH', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Enright', 'Groves', '39 Colo.App. 39, 560 P.2d 851 (1977)', 'Torts', 'The Plaintiff (Enright) lived in a town with a "dog leash" ordinance where Defendant (Groves) was a police officer. Plaintiff''s dog was found to be off its leash and defendant found out. Defendant demanded plaintiff''s drivers license, to which plaintiff refused. Defendant demanded it once more, informing Plaintiff that if it wasn''t produced she would be going to jail. After Plaintiff refused again, Defendant arrested her.', 'Trial Court: In favor of Plaintiff ($500 Actual, $1000 Exemplary)
Appeal: In favor of Plaintiff', 'Is it false imprisonment if the police arrest someone for a violation which the officer does not have probable cause to pursue?', 'No; Ruling Affirmed', 'The defense based on arrest for and conviction of a specific offense is invalid if the arresting "offense" is beyond of the scope of the original offense?', '', 'EnrightVGroves', 'The elements of false arrest are...
- a willful detention of a person
- against the consent of the person
- without the authority of the law');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Volker Court, LLC', 'Santa Fe Apartments, LCC', '130 S.W.3d 607 (2004)', 'Contracts', 'In September of 2001, plaintiff (Lambi) began expressing interest in an apartment complex owned by defendants (Atkins brothers). One of the brothers responded to the offer expressing interest, but rejecting the terms of the offer on the basis that the price was too low. After subsequent communicatioins, the brother replied to plaintiff laying out two possible offers that could be acceptable stating that the other brother was not interested and the included offers would be acceptable if he was able to get them in writing and present them to him. 

Plaintiff took these suggestions as official offers and replied to the letter stating that he accepted and attempting to move forwards with the sale. The defendants rejected this, denying that any official offer had been made. Plaintiff filed a lawsuit agianst defendants for breach of contract.', 'Trial Court: In favor of Defendant (Summary Judgment)
Appeal: In favor of Defendant', 'Do suggestions for an acceptable offer constitute an offer?
Is a stated number binding when one party indicates that others need to be consulted?', 'No; Affirmed', 'A manifestation of willingness to enter into a bargain is not an offer if the person to whom it is addressed knows or has reason to know that the person making it does not intend to conclude a bargain until he has made further manifestation of assent.', 'Defendant was clear multiple times throughout the letters that his brother would have to be consulted and agree to any terms of an offer before it could be fully made. The inclusion of this conditional occludes the possibility that the offer could be binding.', 'VolkerVSantaFe', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Lucy', 'Zehmer', '196 Va. 493, 84 S.E.2d 516 (1954)', 'Contracts', 'The plaintiffs W. O. Lucy and J. C. Lucy purchased a plot of land from defendants A. H. Zehmer and his wife in Dinwiddie county containing 471.6 acres of land for $50,000.
The defendants drafted and signed the contract for the purchase stating "We hereby agree to sell to [plaintiff] the Ferguson Farm complete for $50,000.00, title satisfactory to buyer."
The defendants claim that they thought the offer was made in jest and, having had a few drinks, composed and signed the contract. Further, they claim that the plaintiff was never delivered the contract and instead came by and picked it up and offered the defendant $5 to bind the bargain. The defendant refused, at that point realizing for the first time that the offer was sincere. The plaintiff left the property insisting that the purchase had been completed.
Seven or eight years earlier, plaintiff had tried to purchase the farm from defendant for $20,000 and defendant had verbally agreed, then backed out.', 'Trial Court: In favor of Defendant
Appeal: In favor of Plaintiff (Reversed and remanded)', 'Can a written and signed contract be voided based on an internal and not obviously evident intention not to agree to the terms by one of the parties?', 'No; Reversed and remanded', 'An agreement between two persons is exclusively judged from the expressions of their intentions which are communicated between them.', 'An agreement or mutual assent is essential to a valid contract but the law imputes to a person the intention corresponding to the reasonable meaning of his words and acts. If his words and acts, judged by a reasonable standard, manifest an intention to agree, it is immaterial what may be the real but unexpressed state of his mind.', 'LucyVZehmer', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Continental Laboratories', 'Scott Paper Co', '759 F. Supp. 538, aff''d, 938 F.2d 184 (8th Cir. 1991) (1990)', 'Contracts', 'The defendant (Scott Paper Co) were looking to enter a contract with plaintiff (Continental Laboratories) in which plaintiff would provide hotel amenity products for defendant. After extensive verbal negotiations, the parties reached an agreement on terms. Plaintiff took this to be a binding verbal agreement, while defendant contended that any contract would need to be written before it would be finalized. Therefore, when plaintiff pulled out of the deal before the written contract was finalized, defendant sued them for breach of contract.', 'Trial Court: In favor of defendant
Appeal: In favor of defendant', 'Is a verbal agreement binding if one party believes that it will not be binding until it is written and signed and acts accordingly?', 'No; Affirmed', 'If one of the parties understands the agreement to not be finalized until it is written and signed, then a basic verbal agreement is not binding.', 'In ascertaining whether the parties intended to be bound prior to execution of a written document, the court should consider the following factors:
1. whether the contract is of a class usually found to be in writing;
2. whether it is of a type needing a formal writing for its full expression;
3. whether it has few or many details;
4. whether the ammound is large or small;
5. whether the contract is common or unusual;
6. whether all details have been agreed upon or some remain unresolved; and 
7. whether negotiations show a writing was discussed or contemplated', 'ContinentalVScott', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Stepp', 'Freeman', '119 Ohio App. 3d 68, 694 N.E.2d 792 (1997)', 'Contracts', 'The defendant (Freeman) ran a lottery group that would, when the lottery reached over $8 Million, purchase a total of 2 tickets each for its 20 members. The membership of this group was capped at 20 people, with a waiting list for when a member would leave the group. Leaving the group was also a semi-formalized process in which defendant would consult any member that hadn''t paid in and was interested in leaving before they were removed from the pool.

The plaintiff (Stepp) was a longstanding member of this lottery pool. He also had a role in the group of collecting the tickets after they had been purchased and photocopying them to distribute to each of the group''s members.

On Wednesday, March 3, 1993, the group won a $8 Million jackpot. Prior, defendant and plaintiff got into a work-related dispute that led defendant to abstain from telling plaintiff that the pool was purchasing tickets or collect money from him; telling another member "Stepp hasn''t come around". When the group won, they split the money 19 ways and plaintiff sued for breach of contract.', 'Trial Court: In favor of plaintiff (Objections raised by defendant and overruled)
Appeal: In favor of plaintiff', 'Can an unstated, implied understanding between partities constitute an implied-by-facts contract and does that entitle a party to damages on breach?', 'Yes; Judgement Affirmed', 'The surrounding context around an implied and unstated agreement can give it the weight of a legally binding contract', '', 'SteppVFreeman', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Brown', 'Kendall', '60 Mass. (6 Cush.) 292 (1850)', 'Torts', 'The plaintiff and defendant''s dogs where fighting and, in order to break up the fight, the defendant picked up a stick to hit the dogs to separate them. While raising the stick, the defendant struck the plaintiff, who was standing behind him, in the eye. 

The defendant was acting lawfully, and there was no indication of unlawful intent', 'Jury Trial: In favor of Plaintiff
Appeal: In favor of Defendant (New Trial Ordered)', 'Does the defendant hold the burden of proof when an unintended consequence results from a lawful act without unlawful intentions?', 'No; New Trial Ordered', 'The plaintiff holds the burden of proving that a defendant acted either unlawfully or carelessly', 'If an act is lawful and a purely accidental injury arrises, the actor cannot be held liable', 'BrownVKendall', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Wagner', 'State', '2005 UT 54, 122 P.3d 599 (2005)', 'Torts', 'The plaintiff (Mrs. Wagner) was standing in line at K-Mart when Mr. Giese, a mentally disabled man who was on a supervised visit to the store as part of his treatment, grabbed her by the head and threw her to the ground.', 'Trial Court: In favor of Defendant
Appeals: In favor of Defendant', 'Does battery require that the defendant intended to harm or offensively contact (dual intent) beyond simply intent to make contact (single intent)?', 'No; Previous Ruling Affirmed', 'A defendant does not need to intend an action to be harmful in order to be found laible for battery; instead simply requiring an intent to touch the plaintiff', 'The defendant would not be capable of having an intention of harming the plaintiff, yet the simple act of intending to come into contact with the defendant results in liability', 'WagnerVState', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Talmage', 'Smith', '101 Mich. 370, 59 N.W. 656. (1894)', 'Torts', 'The defendant (Charles Smith) had on his property multiple sheds. One day he came out and saw a number of boys on top of his sheds and ordered them to get down. After they had, he discovered two more boys on the roof of another one of his sheds, though he claims he only saw one of them. 
The defendant picked up a stick and threw it at one of the boys. The stick missed and hit the plaintiff in the eye, resulting in the plaintiff being blinded.', 'Trial Court: In favor of plaintiff
Appeal: In favor of plaintiff', 'Was the intent of the defendant to hit somebody with the stick, and was that exessive force given the facts?', 'Yes; Judgment Affirmed', 'The fact that an injury from a tort resulted to someone other than the intended target does not relieve the defendant of liability', '', 'TalmageVSmith', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Meyer', 'Uber Technologies, Inc', '868 F.3d 66 (2017)', 'Contracts', 'The plaintiff (Meyer) signed up for and used the defendant''s (Uber''s) app to request 10 rides. Afterwards, Meyer accused Uber of engaging in price fixing and prepared to try to take Uber to trial over the charge. Uber requested a motion to compel arbitration per their terms of service agreement. Meyer objected to this on the grounds that the terms of service were not made obvious enough when he was registering for the app. 
The terms of service where situated as "browsewrap" terms meaning that a user was given the option to view the terms, but where not forced to, and would "sign" the contract based on clicking "Register".
The district court sustained this objection and denied the motion to compel arbitration.', 'Pre-trial: Uber motion to compel arbitration -> District court denies
Appeal: Uber appeals this denial -> Denial overruled (Vacated and remanded)', 'Does a "browsewrap" terms of service agreement provide users enough opportunity to read and understand the contractual nature of using a website or app?', 'Yes; Vacated and remanded', 'A reasonable and competent user should be able to understand the contractual and transactional nature of using websites with a "browsewrap" terms of service', 'Inasmuch as consumers are regularly and frequently confronted with non-negotiable contract terms, particularly when entering into transactions using the internet, the presentation of these terms at a place and time that the consumer will associate the initial purchase or enrollment, or the use of, the goods or services from which the recipient benefitsat least indicates to the consumer that he or she is taking such goods or employing such services subject to additional terms and conditions that may one day affect him or her', 'MeyerVUber', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('McGuire', 'Almy', '297 Mass. 323, 8 N.E.2d 760. (1937)', 'Torts', 'The plaintiff was employed to take care of the defendant as a registered nurse. The plaintiff was on "24 hour duty" watching the defendant. One day, the plaintiff heard commotion coming from the defendant''s room and found that she had broken her furniture and was threatening anyone who would come into the room with the leg of a table. When the plaintiff entered the room to disarm the defendant and remove the debris, the defendant struck her in the head.', '', 'Can a person who is considered clinically insane be held liable for torts?', 'Yes; Judgement for the plaintiff', 'In so far as a particular intent would be liable to hold a normal person liable, an insane person, in order to be liable, must have been capable of entertaining the same intent as well as, in fact, entertaining it.', 'The intent of the defendant is crucial in determining liability of a tort, and therefore for a mentally ill defendant the question should be whether they have the capability to have intent as well as whether they actually have the intent.', 'McGuireVAlmy', 'At the time, it was a case without precident as to whether a mentally ill person could be held liable for torts.');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Beard Implement Co', 'Krusa', '208 Ill. App. 3d 953, 567 N.E.2d 345 (1991)', 'Contracts', 'Defendant (Krusa) owned a farm with various pieces of farm equipment. Defendant''s combine broke down and he proceeded to buy a new one. Defendant went to plaintiff (Beard Implement Co) to purchase a new combine and, after some negotiations, signed an order sheet to purchase the new combine for $52,800 and the value of the defendant''s current combine. The defendant had some misgivings, and left the plaintiff with the order sheet (not yet signed by plaintiff) and a check for a 10% downpayment (not yet dated by defendant). After a couple of days, defendant found another dealer who offered a different combine for a lower price. He accepted, believing that since the check hadn''t been dated and the contract hadn''t been signed by plaintiff he was under no obligations. Plaintiff disagreed and sued for breach of contract.', 'Trial Court: In favor of Plaintiff
Appeal: In favor of Defendant (Reversed)', 'In order for a contract to be enforceable, do all subsequent steps laid out in the contract need to be fulfilled?', 'Yes; Reversed', '', 'No contract ever existed between defendant and plaintiff because plaintiff never accepted defendant''s offer to purchase the combine because the purchase order defendant signed required a "dealer" signature on behalf of plaintiff which was not filled out.', 'BeardVKrusa', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('State Rubbish Collectors Ass''n', 'Siliznoff', '38 Cal.2d 330, 240 P.2d 282 (1952)', 'Torts', 'Defendant operated trash collection for Acme Brewing Company and came into conflict with Plaintiff, who considered this collection to be encroaching on their territory. A member of Plaintiff told defendant "We will give you till tonight to get downt o the board meeting and make some kind of arrangements or agreements about Acme Brewery, or otherwise we are going to beat you up". Defendant did go to the meeting and made an agreement, but backed out claiming to have been compelled under duress.', 'Trial Court: In favor of Defendant on claim and counterclaim ($1,250 general and special damages and $4,000 punitive damages)
Appeal: In favor of Defendant (Affirmed)', 'Is the Defendant owed recovery for the IIED he suffered, even in the absense of accompanying physical injury?', 'Yes; Ruling Affirmed', 'In cases where mental suffering constitutes a major element of damages it is anomalous to deny recovery because the defendant''s intentional misconduct fell short of producing some physical injury;.', '', 'RubbishVSiliznoff', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Western Union Telegraph Co', 'Hill', '2005 UT 54, 122 P.3d 599 (2005)', 'Torts', 'The plaintiff (Mrs. Wagner) was standing in line at K-Mart when Mr. Giese, a mentally disabled man who was on a supervised visit to the store as part of his treatment, grabbed her by the head and threw her to the ground.', 'Trial Court: In favor of Defendant
Appeals: In favor of Defendant', 'Does battery require that the defendant intended to harm or offensively contact (dual intent) beyond simply intent to make contact (single intent)?', 'No; Previous Ruling Affirmed', 'A defendant does not need to intend an action to be harmful in order to be found liable for battery; instead simply requiring an intent to touch the plaintiff', 'The defendant would not be capable of having an intention of harming the plaintiff, yet the simple act of intending to come into contact with the plaintiff results in liability', 'WesternUnionVHill', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Big Town Nursing Home, Inc', 'Newman', '461 S.W.2d 195 (1970)', 'Torts', 'Plaintiff (Newman) was an elderly man who was consigned to defendant (Big Town Nursing Home). In the admission papers, the nursing home indicated that he would not be forced to stay there against his will. However, when plaintiff attempted to leave, he was forbidden from doing so. After several more attempts in which he was forcably brought back, the defendant began strapping plaintiff into a chair, locking up his clothes, and did not provide him access to a doctor. After 51 days, plaintiff was able to escape and make it to Dallas. He had lost 30 lbs in the days in which he was retained', 'Trial Court: In favor of plaintiff
Appeal: In favor of plaintiff', '', '', 'False imprisonment is the direct restraint of one person of the physical liberty of another without adequate legal justification', 'Defendant acted in the utter disregard of plaintiff’s legal rights, knowing there was no court order for commitment, and that the admission agreement provided he was not to be kept against his will', 'BigTownVNewman', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Wallace', 'Rosen', '765 N.E.2d 192 (2002)', 'Torts', 'The defendant (Rosen), a teacher at Northwest High School in Indianapolis, was responding to a fire drill that was happening when classes were in session. While escorting students out of the building in accordance with the fire drill procedure, defendant noticed several people at the top of a flight of stairs talking with one another. He walked up to them and called on them to "move it" and, when they did not hear him, touched plaintiff on the back to get their attention. At this point, plaintiff slipped and fell down the stairs and accused defendant of battery for "pushing" her.', 'Trial Court: In favor of defendant
Appeal: In favor of defendant (Affirmed)', 'Did the trial judge err in instructing the jury that "battery is the knowing or intentional touching of one person by another in a rude, insolent, or angry manner" and that "a battery may be recklessly commited where one acts in reckless disregard of consequences?"', 'No; Judgement affirmed', 'Absent expression to the contrary, consent is assumed to all those ordinary contacts which are customary and reasonably necessary to the common intercourse of life', 'The "mere knowledge and appreciation of a risk—something short of substantial certainty—is not intent. The defendant who acts in the belief or consciousness that the act is causing an appreciable risk of harm to another may be negligent, and if the risk is great the conduct may be characterized as reckless or wanton, but it is not an intentional wrong."', 'WallaceVRosen', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Spano', 'Perini Corp', '304 N.Y.S.2d 15 (1969)', 'Torts', 'The plaintiff Spano owned a garage in Brooklyn which was wrecked by a blast of dynamite set off by Perini Corp.
The blast (totaling 194 sticks of dynamite) was set off in a construction site 125 feet from the garage and though it did not result in debris that wrecked plaintiff''s garage, the shockwave of the explosion did shake his garage to the ground.', 'Trial Court: In favor of Defendant
Appeals: In favor of Plaintiff', 'Can someone be held liable for damages caused by blasting that were not the direct result of "physical tresspass" or negligence?', 'Yes; New Trial', 'A blaster holds strict liability for damages resulting from blasting, regardless of whether there was physical trespass or negligence', 'It''s unreasonable to conclude that a company doing dynamite blasting is not liable for damages to adjoining properties unless there is visible, physical debris that entered the property. Such a rule is scientifically unmoored because a blast-wave from an explosion has just as much ability to cause injury. Further, proving negligence is unnecessary as if a shockwave from a construction yard explosion damages nearby property, the blasting was definitionally negligent.', 'SpanoVPerini', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Garratt', 'Dailey', '46 Wash.2d 197, 279 P.2d 1091 (1955)', 'Torts', 'The defendant (a 5 year old named Brian Dailey) was visiting the plaintiff Naomi Garratt (an adult) and the plaintiff''s sister (Ruth Garratt) in the back yard of the plaintiff''s home.
The plaintiff contends that the defendant deliberately pulled a lawn chair out from under her when she went to sit down. However, the trial court accepted the defendant''s explaination that he had pulled the chair for himself to sit in and then, once he realized that the plaintiff was about to sit where the chair used to be, tried to push the chair back under the plaintiff. Unfortunately, the chair was too unwieldy for the defendant to properly move so the plaintiff fell and broke her hip.', 'Trial Court: In favor of Plaintiff (Damages set at $11,000)
Appeal: In favor of Defendant (Remanded for clarification)
Trial Court: In favor of Plaintiff (Damages reset at $11,000)', 'Can a defendant be held liable for battery in the absence of intent if the defendant does not have the knowledge that their action could or would lead to the injury?', 'No; Remanded for clarification', 'A person cannot be held laible for a tort if they do not have the knowledge that their actions could or would lead to an injury.', '', 'GarrattVDailey', 'When the Defendant moved the chair in question, he did not have any wilful or unlawful purpose in doing so and did not intend to injure the plaintiff');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Fujimoto', 'Rio Grande Pickle Co', '414 F.2d 648 (1969)', 'Contracts', 'Plaintiffs worked at Defendant''s pickle company. Defendant offered a contract to plaintiffs that added an annual bonus of 10% of the company''s earnings. When plaintiffs asked for the contract in writing, one was prepared and sent to them. The contract provided no details on how to accept, so plaintiffs simply signed and kept the document. After plaintiffs left the company, they filed for breach of contract claiming that they had never been provided the bonuses. Defendant objected on the grounds that the contracts had never been returned to them, and therefore were not accepted.', 'Trial Court: In favor of Plaintiff ($8,964.25 in damages)
Appeal: In favor of Plaintiff (Affirmed)', 'Can an offer, which by its terms does not specify the means by which they could be accepted, be accepted by a mode other than the return of the signed instruments?', 'Yes; Ruling affirmed', 'A contract may require the acceptor to relay that acceptance by any means; however, in the absence of such a requirement, an acceptors actions (i.e. continuing to work for the company and not mentioning the negotiations again) constitute acceptance.', '', 'FujimotoVRioGrandePickle', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Day', 'Caton', '199 Mass. 513 (1876)', 'Contracts', 'Plaintiff and Defendant each owned equitable interests in ajoining properties. Plaintiff alleges they they build a brick wall, half of which was on Defendant''s vacant lot, with the express understanding that if defendant used it in building on their lot they would renumerate plaintiff for the cost. Defendant used the wall in building on their lot, then denied that such an agreement had ever been formally made.', 'Trial Court: In favor of Plaintiff 
Appeal: In favor of Plaintiff (Exceptions overruled)', 'Can a promise be inferred from the fact that an offerer undertakes and completes the terms of an agreement and the offeree, knowing this completion is done with the expectation that the promise be fulfilled, does not stop them?', 'Yes; Objections overruled', 'The circumstances of each case would necessarily determine whether silence, with a knowledge that another was doing valuable work for his benefit and with the expectation of payment, indicated that consent which would give rise to the inference of a contract.', '', 'DayVCaton', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Norcia', 'Samsung Telecommunications America, LLC', '845 F.3d 1279 (2017)', 'Contracts', 'Plaintiff purchased a phone manufactured by Defendant. Along with the phone was a brochure consisting of a "Standard Limited Warranty" and a EULA, within which was an arbitration clause. The clause stated that the purchaser had the right to opt out of the arbitration clause by providing notice to Defendant within 30 days of the purchase. However, when plaintiff purchased the phone, they carried the phone out and left the brochure and box.

Plaintiff later filed a class action complaint against Defendant, claiming that the specs of the phone had been misrepresented in its advertising. Defendant replied by moving to compel arbitration. ', 'Trial Court: In favor of Plaintiff
Appeal: In favor of Plaintiff (Motion Denied)', 'Does defendant''s inaction constitute agreement to the arbitration clause?', 'No; Motion Denied', 'An offerer must provide some means of manifesting an offeree''s intent to use silence or inaction as means of accepting an agreement or be able to prove such silence or inaction bestowed a benefit on the offeree', 'Defendant made no indication that there was any expectation for plaintiff to agree to the terms as laid out in the brochure. Further, no benefits would be gained or lost by opting out of arbitration. Therefore, inaction on the part of the plaintiff cannot be judged as agreement to the terms.', 'NorciaVSamsung', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Slocum', 'Food Fair Stores of Florida', '100 So.2d 396 (1958)', 'Torts', 'While Plaintiff was shopping at Defendant''s store, Plaintiff alleges that she was insulted by one of defendant''s employees. This insult "', 'Trial Court: In favor of Defendant (Motion to Dismiss based on lack of Cause of Action Granted)
Appeal: In favor of Defendant (Motion to Dismiss Affirmed)', 'Did the insulting language that plaintiff claims caused her injury constitute an actionable invasion of a legally protected right?', 'No; Motion to Dismiss Affirmed', 'A distinction must be drawn between "conduct likely to cause mere ''emotional distress'' and that causing ''severe emotional distress''"', '', 'SlocumVFoodFair', 'It is fo rthe court to determine, in the first instance, whether the conduct would reasonably be regarded as outrageous. Where reasonable men may differ, it is left to the jury as a question of fact.');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Harris', 'Jones', '281 Md. 560, 380 A.2d 611 (1977)', 'Torts', 'Plaintiff was an employee at GM under the supervision of Defendant. Plaintiff suffered from a condition that caused him to stutter and shake his head while trying to pronounce multi-syllable words. Over the course of five months, defendant approached at work and mocked plaintiff''s stutter over 30 times. Defendant additionally repremanded plaintiff two or three times a week, telling him to "not get nervous". Plaintiff requested a transfer multiple times but each time Defendant refused.', 'Trial Court: In favor of plaintiff ($3,500 compensatory damages and $15,000 punative damages)
Special Appeal: In favor of defendant (Judgement Overruled)
Appeal: In favor of defendant (Judgement Affirmed)', 'Was the conduct intentional?
Was the conduct extreme and outrageous?
Was there a casual connection between the wrongful conduct and the emotional distress?
Was the emotional distress severe?', 'Yes on all counts except the last; Judgment Affirmed', '', '', 'HarrisVJones', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Dickinson', 'Dodds', '2 Ch. Div 463 (1876)', 'Contracts', 'Plaintiff was attempting to purchase a property from Defendant for £800. Defendant made an offer subject to acceptance at a specific time. Plaintiff thought on the offer for several days, then decided he wanted to go through. He left a letter of acceptance with defendant''s mother-in-law, but it never reached Defendant. Plaintiff also sent an agent to meet Defendant, but the agent returned to Plaintiff and informed him that between the time that the offer was extended and the Plaintiff attempted to accept, Defendant sold the property to another party. Plaintiff sued for breach of contract for unilaterally revoking the offer.', 'Trial Court: In favor of Plaintiff (Specific Performance)
Appeal: In favor of Defendant', '', '', 'Two minds must be in agreement at one point, the point of agreement', '', 'DickensonVDodds', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Petterson', 'Pattberg', '248 N.Y. 86 161 N.E. 428 (1928)', 'Contracts', 'The plaintiff (Petterson) was the owner of 5301 Sixth Avenue in Brooklyn. Defendant (Pattberg) was the owner of a bond executed by Plaintiff, secured by the mortgage on Plaintiff''s property. Plaintiff sought to pay off $780 of his loan in cash and approached Defendant with the offer. Defendant agreed, offering the unilateral contract in a letter. However, when Plaintiff approached Defendant with the cash, Defendant rebuffed him, informing him that he had sold Plaintiff''s debt and so that deal was off the table.', 'Trial Court: In favor of Plaintiff
Appeal: In favor of Defendant', 'Can an offerer revoke an offer to accept payment so long as that payment hasn''t yet been tendered?', 'Yes; Ruling Reversed', 'Such a contract can be revoked up until the point were the offerer recieves and accepts their payment', '', 'PettersonVPattberg', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Loring', 'City Of Boston', '7 Metc. 409, 48 Mass. 409 (1844)', 'Contracts', 'In May of 1837, Defendant posted a number of advertisements in daily papers in Boston offering "$500 reward... offered for the apprehension and conviction of any person who shall set fire to any building within the limits of the city." The next day, a signed version of the advertisements were published that doubled the reward. After another fire in 1841, Plaintiffs came to suspect Samuel Marriott for the arson and tracked Marriott to New York. After finding him and returning him to Boston, they found all the necessary witnesses and evidence and secured a conviction for the fire. However, when plaintiff requested payment they were denied.', 'Trial Court: In favor of Defendant
Appeal: In favor of Defendant', 'Can an offer that is four years old be accepted because it was never formally withdrawn?', 'No; Judgment Affirmed', 'A unilateral contract is subject to the conditional requirements it lays out as well as a "reasonable time" in which to accept the offer', '', 'LoringVBoston', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Taylor', 'Vallelunga', '171 Cal.App.2d 107, 339 P.2d 910 (1959)', 'Torts', 'In December of 1956, Plaintiff''s father was beaten by Defendant and sued Defendant for battery. However, Plaintiff''s daughter was present and alleged that the events caused her "severe fright and emotional distress." ', 'Trial Court: In favor of Defendant
Appeal: In favor of Defendant', 'Can someone claim IIED for events perpetrated by someone who didn''t know that claimant was there? ', 'No; Judgement Affirmed', 'A claimant can only claim IIED if the perpetrator of the accused tort knew claimant was there', '', 'TaylorVVallelunga', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Dougherty', 'Stepp', '18 N.C. 371 (1835)', 'Torts', 'Plaintiff owned a piece of land that Defendant tried to survey. Defendant entered the land with a surveyor and chain carriers and tried to claim it as his own', 'Trial Court: In favor of Defendant
Appeal: In favor of Plaintiff (Reversed and Remanded)', 'Can a tort for Trespass to Land hold if there was no damage done beyond the "treading down [of] the grass?"', 'Yes; Reversed and Remanded', '', '', 'DoughertyVStepp', '');
INSERT INTO "Cases" ("plaintiff", "defendant", "citation", "course", "facts", "procedure", "issue", "holding", "principle", "reasoning", "label", "notes") VALUES ('Herrin', 'Sutherland', '74 Mont. 587, 241 P. 328 (1925)', 'Contracts', 'Plaintiff alleged that Defendant, while hunting in an adjoining property, fired at water fowl that were flying over both properties. Plaintiff sued Defendant for nominal damages in trespassing in the space over Plaintiff''s property', 'Trial Court: In favor of Plaintiff
Appeal: In favor of Plaintiff', '', '', '', '', 'HerrinVSutherland', '');
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('HardyVLaBelle', 1);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('RansonVKitner', 2);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('ParviVKingston', 1);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('KolodziejVMason', 4);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('KolodziejVMason', 5);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('CohenVPetty', 6);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('CohenVPetty', 7);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('CohenVPetty', 8);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('HawkinsVMcGee', 9);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('HawkinsVMcGee', 6);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('HawkinsVMcGee', 11);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('HawkinsVMcGee', 12);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('FisherVCMH', 15);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('FisherVCMH', 16);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('VolkerVSantaFe', 4);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('VolkerVSantaFe', 11);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('LucyVZehmer', 20);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('ContinentalVScott', 4);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('SteppVFreeman', 4);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('SteppVFreeman', 23);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('BrownVKendall', 6);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('BrownVKendall', 25);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('WagnerVState', 6);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('WagnerVState', 15);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('TalmageVSmith', 25);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('TalmageVSmith', 29);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('MeyerVUber', 30);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('MeyerVUber', 20);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('McGuireVAlmy', 15);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('McGuireVAlmy', 29);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('WesternUnionVHill', 6);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('WesternUnionVHill', 15);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('WallaceVRosen', 15);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('WallaceVRosen', 6);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('SpanoVPerini', 6);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('SpanoVPerini', 42);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('GarrattVDailey', 15);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('GarrattVDailey', 44);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('GarrattVDailey', 29);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('FujimotoVRioGrandePickle', 4);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('DayVCaton', 4);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('DayVCaton', 46);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('DayVCaton', 47);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('NorciaVSamsung', 46);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('LefkowitzVSurplus', 4);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('LefkowitzVSurplus', 11);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('HarrisVJones', 35);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('DickensonVDodds', 49);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('EnrightVGroves', 1);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('RubbishVSiliznoff', 35);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('RubbishVSiliznoff', 48);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('SlocumVFoodFair', 35);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('PettersonVPattberg', 49);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('PettersonVPattberg', 5);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('LoringVBoston', 5);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('LoringVBoston', 9);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('LoringVBoston', 49);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('BeardVKrusa', 4);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('BigTownVNewman', 1);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('TaylorVVallelunga', 15);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('TaylorVVallelunga', 35);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('DoughertyVStepp', 50);
INSERT INTO "CaseSubjects" ("case_label", "subject_id") VALUES ('HerrinVSutherland', 50);
INSERT INTO "CaseOpinions" ("case_label", "opinion_id") VALUES ('PettersonVPattberg', 1);
COMMIT;
PRAGMA foreign_keys=ON;