from pathlib import Path
from typing import Protocol
from DataClasses import CaseBriefData


class CaseBriefRepository(Protocol):
    def ensure_db(self) -> None: ...
    def save(self, data: CaseBriefData) -> None: ...
    def get(self, label: str) -> CaseBriefData: ...
    def export_db_file(self, export_path: Path) -> None: ...
    def restore_db_file(self, backup_path: Path) -> None: ...
    def list_labels(self) -> list[str]: ...
    def list_courses(self) -> list[str]: ...
    def list_subjects(self) -> list[str]: ...
    def add_course(self, course_name: str) -> None: ...
    def remove_course(self, course_name: str) -> None: ...


class CitationResolver(Protocol):
    def cite_label(self, label: str) -> str: ...


class LatexCodec(Protocol):
    def to_tex(self, data: CaseBriefData, cite: CitationResolver) -> str: ...
    def from_tex(self, tex: str) -> CaseBriefData: ...


class TeXCompiler(Protocol):
    def compile(
        self, engine: Path, workdir: Path, outdir: Path, tex_file: Path
    ) -> Path | None: ...
