name: Build and Package CaseBriefs App (PyInstaller)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write   # needed for creating the tag & release and uploading assets

jobs:
  build:
    strategy:
      matrix:
        include:
            # macOS
          - arch: x86_64
            runner: macos-13   # Intel runner
          - arch: arm64
            runner: macos-14   # Apple Silicon runner
          - arch: universal2
            runner: macos-14   # Universal build on Apple Silicon runner
            # Windows
          - arch: amd64
            runner: windows-latest
          - arch: x86
            runner: windows-latest
          - arch: all
            runner: windows-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          # Match Python arch to your matrix (only needed if you truly build 32-bit)
          architecture: ${{ matrix.arch == 'x86' && 'x86' || 'x64' }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pyinstaller

      - name: Build with PyInstaller (spec file)
        shell: bash
        run: |
          pyinstaller CaseBriefs.spec
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            test -d dist/CaseBriefs.app
          else
            test -f "dist/CaseBriefs/CaseBriefs.exe"
          fi

      # macOS packaging
      - name: Package .app as zip (preserve metadata)
        if: startsWith(matrix.runner, 'macos-')
        shell: bash
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent "CaseBriefs.app" "CaseBriefs-${{ matrix.runner }}-${{ matrix.arch }}.zip"
          ls -lah "CaseBriefs-${{ matrix.runner }}-${{ matrix.arch }}.zip"

      # Windows packaging
      - name: Package .exe as zip
        if: contains(matrix.runner, 'windows')
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Compress-Archive -Path "dist/CaseBriefs/*" -DestinationPath "dist/CaseBriefs-${{ matrix.runner }}-${{ matrix.arch }}.zip" -Force
          Get-Item "dist/CaseBriefs-${{ matrix.runner }}-${{ matrix.arch }}.zip" | Format-List *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CaseBriefs-${{ matrix.runner }}-${{ matrix.arch }}
          path: dist/CaseBriefs-${{ matrix.runner }}-${{ matrix.arch }}.zip
          if-no-files-found: error
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CaseBriefs-${{matrix.runner}}-${{ matrix.arch }}
          path: dist/CaseBriefs-${{matrix.runner}}-${{ matrix.arch }}.zip
          if-no-files-found: error

  release:
    name: Create Release & Upload Assets
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out (for tag creation)
        uses: actions/checkout@v4

      - name: Create tag if it doesn't exist
        shell: bash
        run: |
          TAG='${{ inputs.version }}'
          if git ls-remote --tags origin | grep -q "refs/tags/${TAG}$"; then
            echo "Tag ${TAG} already exists."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "${TAG}" -m "Release ${TAG}"
            git push origin "${TAG}"
          fi

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files (debug)
        run: |
          find artifacts -type f -maxdepth 3 -print

      - name: Create GitHub Release (or update if exists)
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: CaseBriefs ${{ inputs.version }}
          body: |
            Universal macOS build artifacts generated by PyInstaller.

            Included builds:
              Macos:
                - x86_64: CaseBriefs-x86_64.zip   (Apple Intel Macs)
                - arm64:  CaseBriefs-arm64.zip    (Apple Silicon: M1/M2/etc)
                - universal2: CaseBriefs-U.zip (Runs on both Intel & Apple Silicon)
              Windows:
                - x86_64: CaseBriefs-x86_64.zip   (Windows 64-bit)
                - xarm64:  CaseBriefs-arm64.zip    (Windows ARM 64-bit)
          draft: false
          prerelease: false

      - name: Upload x86_64 Mac asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/CaseBriefs-macos-x86_64/CaseBriefs-macos-x86_64.zip
          asset_name: CaseBriefs-macos-x86_64.zip
          asset_content_type: application/zip

      - name: Upload arm64 Mac asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/CaseBriefs-macos-arm64/CaseBriefs-macos-arm64.zip
          asset_name: CaseBriefs-macos-arm64.zip
          asset_content_type: application/zip

      - name: Upload universal2 Mac asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/CaseBriefs-macos-universal2/CaseBriefs-macos-universal2.zip
          asset_name: CaseBriefs-macos-universal2.zip
          asset_content_type: application/zip

      - name: Upload x86_64 Windows asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/CaseBriefs-windows-x86_64/CaseBriefs-windows-x86_64.zip
          asset_name: CaseBriefs-windows-x86_64.zip
          asset_content_type: application/zip

      - name: Upload x86 Windows asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/CaseBriefs-windows-x86/CaseBriefs-windows-x86.zip
          asset_name: CaseBriefs-windows-x86.zip
          asset_content_type: application/zip

      - name: Upload all Windows asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/CaseBriefs-windows-all/CaseBriefs-windows-all.zip
          asset_name: CaseBriefs-windows-all.zip
          asset_content_type: application/zip
