name: Build macOS App (PyInstaller)

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: macos-13   # Intel runner
          - arch: arm64
            runner: macos-14   # Apple Silicon runner
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Use the version your project targets; 3.13 if you’re building with 3.13 locally
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Ensure pyinstaller is present even if not in requirements
          pip install pyinstaller

      - name: Build with PyInstaller (spec file)
        shell: bash
        run: |
          # If your spec assumes running from repo root, this is enough:
          pyinstaller CaseBriefs.spec
          # Verify output
          test -d dist/CaseBriefs.app

      - name: Package .app as zip (preserve metadata)
        shell: bash
        run: |
          cd dist
          # Use macOS 'ditto' to preserve resource forks/attrs when zipping .app
          ditto -c -k --sequesterRsrc --keepParent "CaseBriefs.app" "CaseBriefs-${{ matrix.arch }}.zip"
          ls -lah "CaseBriefs-${{ matrix.arch }}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CaseBriefs-${{ matrix.arch }}
          path: dist/CaseBriefs-${{ matrix.arch }}.zip
          if-no-files-found: error
